# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

variables:
- ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
    # 'main' branch: PRD environment
    - template: ../../config-infra-prod.yml
- ${{ if ne(variables['Build.SourceBranchName'], 'main') }}:  
    # 'develop' or feature branches: DEV environment
    - template: ../../config-infra-dev.yml
- name: version
  value: aml-cli-v2 


trigger:
- none

pool:
  vmImage: ubuntu-20.04


resources:
  repositories:
    - repository: mlops-templates  # Template Repo
      name: Azure/mlops-templates # need to change org name from "Azure" to your own org
      endpoint: github-connection # need to set up and hardcode
      type: github
    - repository: rai-vnext-preview  # Template Repo
      name: Azure/rai-vnext-preview # need to change org name from "Azure" to your own org
      endpoint: github-connection # need to set up and hardcode
      type: github

stages:
- stage: DeployTrainingPipeline
  displayName: Deploy Training Pipeline
  jobs:
    - job: DeployTrainingPipeline
      steps:
      - checkout: self
        path: s/
      - checkout: mlops-templates
        path: s/templates/
      - template: templates/tests/unit-tests.yml@mlops-templates
      - template: templates/${{ variables.version }}/install-az-cli.yml@mlops-templates
      - template: templates/${{ variables.version }}/install-aml-cli.yml@mlops-templates
      - template: templates/${{ variables.version }}/connect-to-workspace.yml@mlops-templates
      - template: templates/${{ variables.version }}/register-environment.yml@mlops-templates
        parameters:
          build_type: conda
          environment_name: taxi-train-env
          environment_file: mlops/azureml/train/train-env.yml
      - checkout: rai-vnext-preview
        path: s/
      - task: RegisterRAI
        displayName: 'Register Responsible AI Components'
        inputs:
          azureSubscription: $(ado_service_connection_aml_ws)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            subscription_id=$(az account get-access-token --query tenant --output tsv)
            ./quick-setup.bash $subscription_id $${{ variables.resource_group }} $${{ variables.aml_workspace }}
      - checkout: mlops-templates
        path: s/templates/
      - template: templates/${{ variables.version }}/run-pipeline.yml@mlops-templates
        parameters: 
          pipeline_file: mlops/azureml/train/pipeline.yml
